export const createClientEntrys = [
  // { name: "id", text: "Id Cliente", type: "text" },
  { name: "nombre1", text: "Primer Nombre", type: "text" },
  { name: "nombre2", text: "Segundo Nombre", type: "text" },
  { name: "apellido1", text: "Primer Apellido", type: "text" },
  { name: "apellido2", text: "Segundo Apellido", type: "text" },
  {
    name: "tipoIdentificacion",
    text: "Tipo de identificación",
    type: "select",
  },
  { name: "identificacion", text: "Identificacion", type: "text" },
  { name: "fechaNacimiento", text: "Fecha de Nacimiento", type: "date" },
  { name: "edad", text: "Edad", type: "text" },
  { name: "sexo", text: "Sexo", type: "select" },
  { name: "estadoCivil", text: "Estado Civil", type: "select" },
  { name: "nacionalidad", text: "Nacionalidad", type: "select" },
  { name: "email", text: "Correo Electronico", type: "email" },
  { name: "celular", text: "Telefono Celular", type: "text" },
  { name: "convencional", text: "Telefono Convecional", type: "text" },
  { name: "provincias", text: "Provincia", type: "select" },
  { name: "ciudad", text: "Ciudad", type: "select" },
  { name: "ciudadela", text: "Ciudadela", type: "text" },
  { name: "callePrincipal", text: "Calle Principal", type: "text" },
  { name: "calleSecundaria", text: "Calle Secundaria", type: "text" },
  { name: "manzana", text: "Manzana", type: "text" },
  { name: "villa", text: "Villa", type: "text" },
  { name: "referencia", text: "Referencia", type: "textarea" },
  { name: "formaPago", text: "Forma de Pago", type: "select" },
  { name: "estado", text: "Estado", type: "radio" },
];
